language: python

python:
  - 3.6.5

services:
  - postgresql

addons:
  postgresql: "9.6"

env:
  global:
    - DATABASE_URL=postgres://postgres@localhost/resume
    - BUILD_ON_TRAVIS=true

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE resume;" -U postgres
  - psql -c "CREATE USER resume_user WITH PASSWORD 'password'; GRANT ALL PRIVILEGES ON DATABASE resume TO resume_user" -U postgres
  - psql -c "ALTER USER resume_user CREATEDB;" -U postgres
  - python3 manage.py makemigrations --noinput

script:
  - python manage.py test