version: '3'
services:
  database:
    restart: always
    container_name: resume_database
    image: postgres:latest
  web:
    container_name: resume_web
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --settings=resume.settings.development
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db