version: '3'

services:
  database:
    restart: always
    container_name: resume_database
    image: postgres:latest
    ports:
      - 5432:5432

  web:
    container_name: resume_web
    build: .
    command: >
      bash -c "sleep 5
      && python manage.py migrate --settings=resume.settings.development_docker
      && python manage.py runserver 0.0.0.0:8000 --settings=resume.settings.development_docker"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - database

#  nginx:
#    restart: always
#    ports:
#      - 8000:80
#    volumes:
#      - ./B2R/nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - web